### ISSUE TITLE
This line relies too much on the order of objects which is not guaranteed

### ISSUE THREAD

**Issue by Amri91** [Avaq/node-server-skeleton#24]
https://github.com/Avaq/node-server-skeleton/blob/92035cd19682960fc8cbd5b46df671d646c8305c/src/util/version.js#L19

Callbacks with keys parsable to integers may be reordered.

https://bugs.chromium.org/p/v8/issues/detail?id=164

and semver.satisfies accept integers as ranges.

**Comment by Avaq** [comment]
Thank you for the heads-up @Amri91. I have never used integers in these keys, and this project will be discontinued, so I will not act upon this issue. I'll leave it open to inform those who might happen upon it.
